language: python
os: linux
dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install tox tox-travis codecov

before_script:
  - coverage erase

after_success:
  - codecov
script:
  - tox
